### ISSUE TITLE
UI doesn't load Windows 11

### ISSUE THREAD

**Issue by MRog40** [prayag17/JellyPlayer#115]
**Describe the bug**
 - OS: Windows 11 22H2
- After adding server, UI doesn't load
- Never loads on consecutive launches

**Screenshots**
![image](https://github.com/prayag17/JellyPlayer/assets/47461109/71775ff6-cf0b-4d18-93f3-38b9fad02e2a)

**Comment by prayag17** [comment]
Can you send me a screenshot of the console when you open inspect but right-click on the app?

**Comment by MRog40** [comment]
![image](https://github.com/prayag17/JellyPlayer/assets/47461109/10c292ba-7889-4398-9789-ea87dce48c79)

Maybe 401 is my credentials to server??

**Comment by prayag17** [comment]
No it won't save the wrong credentials and would show error on wrong credentials

**Comment by MRog40** [comment]
It does flash with some UI right when I launch the program, not sure if that's like a placeholder image to make it appear like an instant load though

**Comment by prayag17** [comment]
Yeah that's just the home page skeleton, I am not able to recreate this issue in my setup

**Comment by MRog40** [comment]
Uninstalled removing program data and started over, demo of first time setup and failure:

https://github.com/prayag17/JellyPlayer/assets/47461109/f071b7ec-fb60-40c5-acf4-1996363571ab

Every launch after this is the blank UI and the same console error. Showed also that web client works fine, also Jellyfin official client works fine.

**Comment by prayag17** [comment]
Hey, can temporarily remove Friends from your server and retry?

**Comment by MRog40** [comment]
That worked. So, some library indexing doesn't work compared to other Jellyfin clients

**Comment by prayag17** [comment]
Nah there is something wrong with my blurhash implementation [Friends doesn't have images so it breaks when it gets undefined], meanwhile, run this hotfix so that you can add back Friends tho beware that the title page might also break.

**Comment by dezhishen** [comment]
same bug

the url : $server/Users/Me return 401

jellyfin's version: 10.8.10
client's version: v1.0.0-alpha01

**Comment by prayag17** [comment]
Can you share me your setup's screen recording just like he did

**Comment by dezhishen** [comment]
> Can you share me your setup's screen recording just like he did
![image](https://github.com/prayag17/JellyPlayer/assets/26274059/77c36547-fc3a-49ea-a6d2-65c4afe2f83e)

**Comment by Xavantex** [comment]
I also experience this bug on Windows 10.

**Comment by prayag17** [comment]
Don't use alpha 1, it was a lot buggy

**Comment by Xavantex** [comment]
> Don't use alpha 1, it was a lot buggy

Do recommend building it from master?

**Comment by prayag17** [comment]
Yeah thats the most up-to-date version

**Comment by TheFeelTrain** [comment]
That commit doesn't seemed to have fixed it, just created a different error instead.

![Screenshot_20230916_094850](https://github.com/prayag17/JellyPlayer/assets/12601452/244a2198-b87d-4bd3-907d-83a4bd4a9ba9)

**Comment by prayag17** [comment]
New error, noice some progress. 

Anyways I known this issue for sometime now, I am working on a fix

**Comment by prayag17** [comment]
Can you check now @TheFeelTrain ?

**Comment by TheFeelTrain** [comment]
Looks like that was it. Seems to be good now 👍

**Comment by prayag17** [comment]
Nice, so I am closing this issue now

**Comment by Xavantex** [comment]
While issue is about windows 11, just wanted to notify that I downloaded the latest commit. Sadly it does not seem to work on windows 10 :(

**Comment by prayag17** [comment]
Can you send the error?

**Comment by Xavantex** [comment]
Maybe my NGINX is breaking it, I am also using a self-signed cert, so could be that.
![image](https://github.com/prayag17/JellyPlayer/assets/29485805/04ac98a4-3640-472f-88a6-cda9a89d7108)

**Comment by prayag17** [comment]
Yeah that's the issue, tairi still doesn't allow unsafe https requests

**Comment by prayag17** [comment]
By unsafe https I mean https sites using self signed ssl which is not recognised by browser as official.

**Comment by prayag17** [comment]
Hey, @Xavantex I potentially might have fixed the SSL cert error in the lastest commit. Can you please check?

**Comment by Xavantex** [comment]
Same but different. Don't worry about it mate. Take it whenever it comes on your radar.
![image](https://github.com/prayag17/JellyPlayer/assets/29485805/9ac56446-72e7-4ba0-8dee-d35dba77fea9)

**Comment by prayag17** [comment]
Well at least that's something I can fix. Also you should blue your server ip in those images

**Comment by Xavantex** [comment]
Ah, seems I missed a package from the latest commit. It seems to have fixed some things after retrying. :|
Sorry about that.
I still have failed to load resource errors, but also a few others.
I'll include the logfile. Too much to cover in an image. (also obscured the info as you suggested)
[localhost-1695405382077.log](https://github.com/prayag17/JellyPlayer/files/12703468/localhost-1695405382077.log)

**Comment by prayag17** [comment]
Most of them are the same errors so it's fine. But for the life of it i can't figure out why it says NotSameOrigin , I tried different servers even used reverse proxy to see if that's the issue but it's not. Do you have some security setting turned on in jellyfin?

**Comment by RashikFarhan** [comment]
It looks like a common issue now....tried to install in two different server but same result
![Screenshot 2023-09-23 234907](https://github.com/prayag17/JellyPlayer/assets/142752522/3d92b189-8df1-4c00-8d7c-2085a975d08b)

**Comment by prayag17** [comment]
Can you share a screenshot of the console when running the app with dev command

**Comment by RashikFarhan** [comment]
I don't actually know whats dev command...Using win 10...attached this video if that could be of any help

https://github.com/prayag17/JellyPlayer/assets/142752522/fec059d7-c4f0-4f9f-8e34-1354669c5cc7

**Comment by prayag17** [comment]
I have a feeling that live tv might be causing this issue. I have to check it out tho

**Comment by RashikFarhan** [comment]
I'm really sorry....I should've checked previous discussions...Building up from commit is so much work...I'll wait for alpha 2...Thanks for helping...

**Comment by Xavantex** [comment]
> Most of them are the same errors so it's fine. But for the life of it i can't figure out why it says NotSameOrigin , I tried different servers even used reverse proxy to see if that's the issue but it's not. Do you have some security setting turned on in jellyfin?

Can't say I am, but can return after I have looked into it more.

**Comment by prayag17** [comment]
@RashikFarhan I have created a test release with current patches for Mac and Win so you can try it out. You need to go to release page of this repo to get it.

**Comment by RashikFarhan** [comment]
thank you so so much...It works now...
