### ISSUE TITLE
Better TLS support

### ISSUE THREAD

**Issue by VampiricAlien** [prayag17/JellyPlayer#119]
Trying to connect with https:
[Error] Failed to load resource: Unacceptable TLS certificate (Ping, line 0)
[Error] Failed to load resource: Error performing TLS handshake: An unexpected TLS packet was received. (Ping, line 0)

TLS is self singed CA Certificate

**Comment by prayag17** [comment]
Try using http

**Comment by prayag17** [comment]
I can't currently fix this as it is an issue with Tauri itself and I can't do anything about it

**Comment by prayag17** [comment]
Hey, @VampiricAlien I potentially might have fixed the TLS issue in the latest commit. Can please check?

**Comment by prayag17** [comment]
Not currently but you can run the app on your machine by following instructions in readme

**Comment by prayag17** [comment]
There was some issue with the workflow file when I built the test, but next one will have Linux image

**Comment by prayag17** [comment]
Can you check now if the issue is fixed?

**Comment by prayag17** [comment]
So it is fixed?

**Comment by prayag17** [comment]
I can't find a fix for this, even when using tauri's http client the request gets blocked by the OS. 

I am gonna keep this issue open for now, will be happy to hear suggestions from others regarding this

**Comment by prayag17** [comment]
Nope this doesn't use node backend

**Comment by prayag17** [comment]
Nice to hear that it works. 
Ps. Both are dev build.

That ip might be your device ip, I use react devtools and need to add a script tag pointing to localhost:8097 so that's what it might be
