### ISSUE TITLE
Ability to select none for subtitles

### ISSUE THREAD

**Issue by Taubin** [prayag17/JellyPlayer#123]
**Is your feature request related to a problem? Please describe.**
I have a lot of shows that have subtitles, but my user does not use them. When attempting to play one recently, there was no option to deselect them. I attempted to click on my user settings and it just says "WIP settings"

**Describe the solution you'd like**
The ability to turn off subtitles

**Describe alternatives you've considered**
I mean, I ended up using another client. 

**Additional context**

![subs](https://github.com/prayag17/JellyPlayer/assets/8891792/b58bd707-46c0-4c1a-9253-b31041b33714)

**Comment by prayag17** [comment]
I add an none option

**Comment by prayag17** [comment]
This feat is added now
