### ISSUE TITLE
Doesn't display movies within a collection

### ISSUE THREAD

**Issue by need4swede** [prayag17/JellyPlayer#125]
**Describe the bug**
If your Jellyfin library is set to group movies into collections, then the individual movies within collections won't appear in JellyPlayer.

**To Reproduce**
1. Set Jellyfin to group movies into collections
2. Find a collection in JellyPlayer
3. Unable to see the movies in the collection, or pick a specific movie in a collection to play

**Expected behavior**
1. If item is a collection => show all movies in collection

**Screenshots**
<img width="629" alt="Screenshot 2023-07-10 at 08 28 20" src="https://github.com/prayag17/JellyPlayer/assets/57847545/e6d8719b-d711-4432-b605-4c9b9179dca0">

**Desktop (please complete the following information):**
 - OS: [macOS 13]

**Comment by prayag17** [comment]
The collection Page should display all the collection items
