### ISSUE TITLE
Error "Unspecified proxy lookup failure" 

### ISSUE THREAD

**Issue by tam1m** [prayag17/JellyPlayer#126]
**Describe the bug**
Running JellyPlayer restults in the the error below. 
Just a white window with the error "Unspecified proxy lookup failure".
This happens for both locally built binaries aswell as the prebuild ones from this repo.

**To Reproduce**
1. Follow build instructions in the README or download prebiuld release binary
2. Run the app
3. See error

**Screenshots**
![image](https://github.com/prayag17/JellyPlayer/assets/472185/b3f585e5-bb3f-466e-8f4b-7f844b241e2a)

**Desktop (please complete the following information):**
❯ npm run tauri info

> jellyplayer@1.0.0-alpha0 tauri
> tauri info

[✔] Environment
- OS: Arch Linux Rolling Release X64
✔ webkit2gtk-4.0: 2.40.3
✔ rsvg2: 2.56.2
✔ rustc: 1.70.0 (90c541806 2023-05-31)
✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
✔ rustup: 1.26.0 (2023-05-04)
✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
- node: 20.4.0
- yarn: 1.22.19
- npm: 9.8.0

[-] Packages
- tauri [RUST]: 1.3.0
- tauri-build [RUST]: 1.3.0
- wry [RUST]: 0.24.3
- tao [RUST]: 0.16.1
- @tauri-apps/api [NPM]: 1.4.0
- @tauri-apps/cli [NPM]: 1.4.0

[-] App
- build-type: bundle
- CSP: unset
- distDir: ../dist
- devPath: http://localhost:5173/
- framework: React
- bundler: Vite
2,36s user 0,60s system 45% cpu 6,480s total

**Comment by prayag17** [comment]
![image](https://github.com/prayag17/JellyPlayer/assets/55829513/846838ea-0516-44ad-ba69-f04aae4ccfd7)
I tried recreating your arch setup in a vm but I don't see that issue, I just installed the .deb file for alpha 1 and it ran just fine

**Comment by prayag17** [comment]
Yeah I think this is something to do with the tauri localhost plugin

**Comment by tam1m** [comment]
I can't use the deb package since arch is not based an debian and doesn't use deb. What I don't understand though is, why I can use your AppImage, at least with `GTK_USE_PORTAL=0`, but can't built a working one myself.

I also built a release version with npm run tauri build, but I'm getting the same error

**Comment by prayag17** [comment]
You can use .deb in arch with debtap, and as to why you are not able to build one might have something to do with your os's default browser and webview implementation, what arch based os are you using? And also what is the desktop framework of your os(like gnome, kde)?

**Comment by tam1m** [comment]
Alright, tried the .deb package, but same thing.

I'm on plain archlinux with kde plasma 5.27.6. Default browser is Firefox. How do I get the webview implementation? Wouldn't this be part of webkit2gtk-4.0?

**Comment by tam1m** [comment]
Found something. Since I'm using KDE, `XDG_CURRENT_DESKTOP=KDE` is set. Settings this to anything but `KDE` fixes the problem entirely. Not sure what that means or what causes this in the first place, but running jellyplayer with `XDG_CURRENT_DESKTOP=""` works in all scenarios I tried.

**Comment by prayag17** [comment]
> Wouldn't this be part of webkit2gtk-4.0?

Yeah 

Try running with GDK_BACKEND=wayland

**Comment by prayag17** [comment]
@tam1m can you try removing "http" from allowlist in tauri.conf.json https://github.com/prayag17/JellyPlayer/blob/main/src-tauri/tauri.conf.json#L27 and running it? The issue seems to be related with webkit-gtk

**Comment by prayag17** [comment]
Hey, @tam1m can you see if this issue still persists with the new commit
