### ISSUE TITLE
Fullscreen view switches back to windowed view when clicking element in library

### ISSUE THREAD

**Issue by foss-** [prayag17/JellyPlayer#137]
macOS 13.5
JellyPlayer 1.0.0 (20230706.101539)

**Describe the bug**
Fullscreen view switches back to windowed view when clicking element in library.

**To Reproduce**

1. open music section when in fullscreen
2. Click on an album

**Expected behavior**
Open album details while staying in fullscreen.

**Current behavior**

JellyPlayer switches to windowed mode once an album is clicked. This is not limited to the music section. When viewing movies in fullscreen and clicking on a movie JellyPlayer also switches to windowed mode.

**Comment by prayag17** [comment]
This should be fixed now
