### ISSUE TITLE
Installing deb does not work on ubuntu 22 or later

### ISSUE THREAD

**Issue by sevenrats** [prayag17/JellyPlayer#172]
install the deb with dpkg and attempt to run it.
Install succeeds but it can't find some links: 
libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by prayag17** [comment]
Are you using alpha 1? If yes then don't alpha 1 is very unstable, alpha 2 will be published soon but till then you can run app by manually building it on your system (follow steps in readme to do so)

**Comment by ilkersigirci** [comment]
Alpha 2 doesn't have any deb file. Is it a release problem?

**Comment by prayag17** [comment]
It is still building.
Edit: should we put now

**Comment by ilkersigirci** [comment]
I see it now. Thank you

**Comment by prayag17** [comment]
is this issue fixed?

**Comment by sevenrats** [comment]
yes this is resolved in alpha 2
