### ISSUE TITLE
App Freezes a lot

### ISSUE THREAD

**Issue by SudoVanilla** [prayag17/JellyPlayer#174]
When using the AppImage file provided in releases, most tasks in JellyPlayer ends up freezing the app and then resulting to a gray solid background.

Sometimes even basic navigation freeze,

When this occurs, the console does output the same message:
```bash
** (jelly-player:458070): WARNING **: 10:05:38.695: atk-bridge: get_device_events_reply: unknown signature
```

> I understand the app in in alpha.

**Comment by prayag17** [comment]
Don't use alpha 1 it is very unstable, run app using pnpm(follow readme for info)

**Comment by SudoVanilla** [comment]
Hmm, I'll give it a try with bun.

**Comment by SudoVanilla** [comment]
It runs smoothly when running with current version from GitHub, but when playing an episode or movie, it only shows a blank screen while playing the audio.

**Comment by prayag17** [comment]
Audio playback is not yet implemented

**Comment by prayag17** [comment]
@SudoVanilla You can test audio playback with the latest commit. Also the app might feel a bit laggy in dev mode so build it and run

**Comment by SudoVanilla** [comment]
I already said audio playback works, the issue is video playback.

**Comment by prayag17** [comment]
Previously audio files would open up video player that's why you got the black screen

Video files are playing perfectly fine on my machine, weird.

**Comment by SudoVanilla** [comment]
I will check out the latest commit.

**Comment by SudoVanilla** [comment]
![image](https://github.com/prayag17/JellyPlayer/assets/51213244/602492ec-b93b-466c-b48a-58e75d0b7dc9)

Yeah, still outputting a black screen with working audio.

**Comment by prayag17** [comment]
Huh, what error do you get on running?

**Comment by SudoVanilla** [comment]
Only error that appears:
```bash
[BABEL] Note: The code generator has deoptimised the styling of /home/korbs/JellyPlayer/src/assets/logo.svg as it exceeds the max of 500KB.
```
Although, that is not related to the player.

No other errors appear.

**Comment by ilkersigirci** [comment]
> Hmm, I'll give it a try with bun.

Did you successfully installed and built with using bun? I am on bun 1.0.3 and I got following error
```bash
error: Declarations with the name arguments cannot be used with esm due to strict mode

const [bin, script, ...arguments] = process.argv
                       ^
/home/ilker/Documents/Github_Repos/JellyPlayer/node_modules/@tauri-apps/cli/tauri.js:10:24 246
error: script "tauri" exited with code 1 (SIGHUP)
```

**Comment by prayag17** [comment]
Bun is not a supported runtime for application
