### ISSUE TITLE
Movies Library Not showing all movies

### ISSUE THREAD

**Issue by hackmonker** [prayag17/JellyPlayer#183]
The Movies library is showing only one movie even though there are a few more present. same case for music. shows looks like is showing all. All of them can be played from homescreen and even searched but cant be seen in library

![image](https://github.com/prayag17/JellyPlayer/assets/46002790/98a523f2-38b3-48b6-9ea5-73318c5096f8)
![image](https://github.com/prayag17/JellyPlayer/assets/46002790/1bbfc878-8ff6-4e77-83c9-b376b590423a)

![image](https://github.com/prayag17/JellyPlayer/assets/46002790/0b2d623b-035b-43f4-a884-3a4033d7cccc)
![image](https://github.com/prayag17/JellyPlayer/assets/46002790/c804b51d-e88d-43e0-8e31-50cd7b400fac)

**Comment by prayag17** [comment]
Hmm weird, I just noticed it. I will check it out

**Comment by prayag17** [comment]
I am not able to find a fix for this. Seems like an API issue but it seems to work just fine on a browser just refuses to work here for some unknown reason

**Comment by prayag17** [comment]
Fixed
