### ISSUE TITLE
Subtitle Support

### ISSUE THREAD

**Issue by GwnMichael** [prayag17/JellyPlayer#184]
If possible, maybe add subtitle support? That would be really helpful / nice

**Comment by prayag17** [comment]
Subtitles are already supported

**Comment by GwnMichael** [comment]
> Subtitles are already supported

My bad, i meant to say that it would be nice to have the option to select a certain subtitle, or turn it off completely enc

**Comment by prayag17** [comment]
You can select subtitles from the title page for now, I have yet to implement changing subtitle, video, audio track from the player itself
