### ISSUE TITLE
Media player only has audio output

### ISSUE THREAD

**Issue by ohitstom** [prayag17/JellyPlayer#189]
Attempting to play a video gives the error below, no video, only audio! miniplayer doesnt work, it seems to be fine in browser and using jellyfin media player...

![image](https://github.com/prayag17/JellyPlayer/assets/22730962/a58a8c07-29b2-4f22-a8a9-50d622649772)

**Comment by prayag17** [comment]
Can you check if this is still an issue?

**Comment by ohitstom** [comment]
> Can you check if this is still an issue?

will try when I get some time, I assume there's a new release?

**Comment by prayag17** [comment]
Yeah

**Comment by ohitstom** [comment]
> Yeah

same issue! but it doesnt seem to be all media...
![image](https://github.com/prayag17/JellyPlayer/assets/22730962/88b16db0-1d20-44c6-ad88-12e9efd94e10)
![image](https://github.com/prayag17/JellyPlayer/assets/22730962/9b9be385-8d2e-422b-ae8a-fd42944101d5)
![image](https://github.com/prayag17/JellyPlayer/assets/22730962/19b876df-5dad-45d6-ab0c-c522864e87e7)

**Comment by prayag17** [comment]
Can see if the console still throws some error?

**Comment by ohitstom** [comment]
hi sorry i just woke up, do you still want me to do this?

**Comment by prayag17** [comment]
Yeah, I pushed the commit to a different issue but used the wrong issue no

**Comment by ohitstom** [comment]
> Yeah, I pushed the commit to a different issue but used the wrong issue no

![image](https://github.com/prayag17/JellyPlayer/assets/22730962/2bd0c4d9-89f0-455c-8f30-48eb419bdd9a)
Pastebin of object: https://pastebin.com/UkcWRVQn

**Comment by ohitstom** [comment]
thats with using the local serve btw if i use my proxy i get this:
![image](https://github.com/prayag17/JellyPlayer/assets/22730962/e5b32158-3042-489b-8ac0-a1399447968e)
