### ISSUE TITLE
Hi , The problem of decoding

### ISSUE THREAD

**Issue by jackloves111** [prayag17/JellyPlayer#200]
作者大佬你好，请问这个播放器使用的是服务器端解码，还是用的客户端解码？这个对我来说比较重要，或者是否可以增加选择解码的选项呢？

Machine translation:
Hello authoritative person, may I ask if this player uses server-side decoding or client-side decoding? This is important to me. Or could there be an option to choose between decoding methods?

**Comment by prayag17** [comment]
If by decoding you mean video decoding then the player direct plays(decode on client) if video codec is supported by your device, and transcodes if not supported

**Comment by jackloves111** [comment]
Yes, it's video decoding. You mean the decoding is automatic, right? The main thing I want to confirm is that the video uses a graphics card for hardware decoding. Not the CPU

**Comment by jackloves111** [comment]
144/2000 
My server CPU and graphics card price low-end, all I need to play directly, so the use of the client's graphics card and CPU for decoding. Currently with the page to play, often forced transcoding, especially HEVC format

**Comment by prayag17** [comment]
If you use windows or Macos the client is able to play high bitrate, HDR HEVC files just fine using Direct play. I have not tested this on linux

**Comment by jackloves111** [comment]
> If you use windows or Macos the client is able to play high bitrate, HDR HEVC files just fine using Direct play. I have not tested this on linux

OK，i am windows.I'll try and get back to you

**Comment by jackloves111** [comment]
hi。After my testing, I found that it was indeed played using the client's graphics card, so there was no stuttering. And I use web pages for transcoding, which is stuttering. But another problem is that if the video decoded by the client is Dolby Vision, the color of the picture will be green because it is not transcoded and my monitor does not support HDR

**Comment by prayag17** [comment]
HDR settings should be managed by windows(as JellyPlayer uses native renderer), so you need to dig into windows settings to disable HDR.

**Comment by jackloves111** [comment]
OK。got it
