### ISSUE TITLE
Cover Art not as Sharp as Source Images

### ISSUE THREAD

**Issue by qvattr0** [prayag17/JellyPlayer#211]
**Describe the bug**
I'm not sure if that's a bug, but a general thing I've noticed is that the quality of cover art for media is always lower resolution compared to the media files stored on the drive or shown in Jellyfin Media Player.

**To Reproduce**
1. Go to any piece of media stored on the device
2. Visually inspect the quality of the cover art

**Expected behavior**
The image quality should be very similar if not exactly the same when compared to what's displayed on Jellyfin Media Player or the source cover-art image file.

**Screenshots**
![image](https://github.com/prayag17/JellyPlayer/assets/141742777/fe44d729-135d-4a2a-9907-8363ca957dc8)
Cover art for John Wick Chapter 4 on JellyPlayer.

![image](https://github.com/prayag17/JellyPlayer/assets/141742777/e17b4478-a0a9-43a1-a24d-3b9e32a3cf13)
The same media file but on Jellyfin Media Player. Notice the drastic difference in visual fidelity of the cover art.

**Desktop:**
 - OS: Windows 11
 - Version: 22H2
 - JellyPlayer Version: Alpha 2

**Comment by prayag17** [comment]
I decreased the image quality during testing api methods but forgot to change it. I will fix it
