### ISSUE TITLE
Don't show static JellyPlayer logo in the top left

### ISSUE THREAD

**Issue by foss-** [prayag17/JellyPlayer#241]
In order to have a clean UI it would be preferable to not show the logo in the top left for all views. Just checked to see what Plex does in PlexHTPC and I am not seeing a logo anywhere. Probably for the same reason: to provide a distraction free UI.

<img src="https://github.com/prayag17/JellyPlayer/assets/5708172/8926f118-67f4-4059-aceb-445ccc6547bf" width="450">

**Comment by prayag17** [comment]
I will take this into consideration

**Comment by prayag17** [comment]
It does look more cleaner without the logo there, so I have removed it. Thank you :).
