### ISSUE TITLE
Windows ARM64 package

### ISSUE THREAD

**Issue by kylehase** [prayag17/JellyPlayer#245]
**Is your feature request related to a problem? Please describe.**
There is currently no package for Windows on ARM.

**Describe the solution you'd like**
It would be great to include a Windows on ARM64 package along with the other packages.

**Additional context**
Windows on ARM64 is gaining popularity due to it's greater efficiency vs X64 and in part to Apple's success with their M chips. Even Microsoft has now released a Surface ARM 2-in-1 PC.

**Comment by prayag17** [comment]
Arm builds are currently not possible since github-actions doesn't support it and I don't have an windows arm machine to build binaries on.
