### ISSUE TITLE
Subtitle Display and Styling Problems

### ISSUE THREAD

**Issue by AkkoYK** [prayag17/JellyPlayer#253]
#### Problem
I've encountered an issue with the subtitles in your player. Specifically, the advanced features such as dual-language display (upper and lower) & (screen top and bottom) and custom styling (font, size, color, etc.) do not seem to be working as expected.

#### Expected Behavior
I expected the subtitles to be displayed with dual-language support (upper and lower) & (screen top and bottom) and with the custom styles including font, size, color, etc applied as specified in the ASS subtitle file.

![屏幕截图 2024-01-18 211235](https://github.com/prayag17/JellyPlayer/assets/69787631/36c09519-e8c3-4ef8-bc44-39464a808970)
![屏幕截图 2024-01-18 210949](https://github.com/prayag17/JellyPlayer/assets/69787631/ded0deac-88c1-4842-bf23-0431e3f065ec)
(ScreenShots in jellyfin-media-player)

#### Actual Behavior
The subtitles are currently overlapping, and the custom styles (font, size, color, etc.) are not being applied.

![屏幕截图 2024-01-18 210122](https://github.com/prayag17/JellyPlayer/assets/69787631/de257e22-2fa1-4ce5-b6ec-862ecb1d6f51)
![屏幕截图 2024-01-18 210207](https://github.com/prayag17/JellyPlayer/assets/69787631/f3971123-a9bc-40d7-8c1b-d8b0765e922c)
(ScreenShots in JellyPlayer)

#### Steps to Reproduce
1. Play a video with an ASS subtitle file that uses dual-language display and custom styling or the other advanced features.
2. Observe the behavior of the subtitles.

**Comment by prayag17** [comment]
.ass subtitle support is planned and should be added in Alpha 3
