### ISSUE TITLE
playing track from album view loads a blank page

### ISSUE THREAD

**Issue by foss-** [prayag17/JellyPlayer#266]
**Describe the bug**
1. Open a music album
2. click track to play it
Currently: blank page loads

**Expected behavior**
Play music track

**Screenshots**
<img src="https://github.com/prayag17/JellyPlayer/assets/5708172/bf8c1186-ab5d-457d-ba3b-6942c452c27b" width="350">

**Desktop (please complete the following information):**
 - OS: macOS 13.6.4
 - 0.0.4-dev (20240224.092219)

**Comment by prayag17** [comment]
Is this still an issue?

**Comment by foss-** [comment]
Yes persisting.

**Comment by prayag17** [comment]
closing this in favor of #338
