### ISSUE TITLE
jellyplayer unable to connect to jellyfin server

### ISSUE THREAD

**Issue by priyajit4u** [prayag17/JellyPlayer#285]
Jellyplayer as of now (tested on latest update) is unable to access my self hosted jellyfin server. I am hosting my jellyfin server in my homelab and all the other browsers/mobile app are able to connect to my sever via https://jellyfin.mydomain.com however jellyplayer is showing "Provided server address is not a Jellyfin server."

![4B74E559-FB9D-4047-AED2-75F717309762](https://github.com/prayag17/JellyPlayer/assets/134056924/1b5010fb-e9f3-4078-b11f-3f21abb88cbf)

**Comment by prayag17** [comment]
can you post a screenshot of console (right click > inspect > console)?

**Comment by prayag17** [comment]
closing this in favour of #210
