### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by IrishBumfuzzle** [prayag17/JellyPlayer#3]
Consider updating the readme now that you are using the vue for frontend, can't figure out what to do to run this

**Comment by prayag17** [comment]
It will take me some time to do so as I am currently trying to find a way to compile JellyPlayer to M1 Macs and RPI on my machine which runs Linux, but it seems like there is no way to cross-compile python and I might just end up switching to a language that does that. If you know a solution to this I would to check it out. Though JellyPlayer should run on M1 macs too

**Comment by prayag17** [comment]
for right now though just go to jellyplayer/jellyplayer-jellyfin-vue and run `npm install` after that if you are on windows then run `npm run build` with Windows Subsystem for linux, after that go back to the root of project and run `pip install poetry` and then run `poetry run python jellyplayer/__init__.py` then app will run

**Comment by jjgalvez** [comment]
> for right now though just go to jellyplayer/jellyplayer-jellyfin-vue and run `npm install` after that if you are on windows then run `npm run build` with Windows Subsystem for linux, after that go back to the root of project and run `pip install poetry` and then run `poetry install` then run `poetry run python jellyplayer/__init__.py` app will run

FYI I just ran python -m jellyplayer.  At some point you may want to actually create an endpoint with peoety and have it build a proper script to start it for you

**Comment by prayag17** [comment]
The documentation for running and building JellyPlayer have been updated
