### ISSUE TITLE
Black Screen with audio

### ISSUE THREAD

**Issue by BNX070** [prayag17/JellyPlayer#310]
**Describe the bug**
Getting a blank black screen with only audio playing, bug seems to be only with HEVC files as H264 content plays fine. The native jellyfin app doesn't have this issue so it seems to be related with JellyPlayer.

**Expected behavior**
Video should play

These are the filetypes having the black screen issue
![image](https://github.com/prayag17/JellyPlayer/assets/63129604/583917fd-f596-416e-999e-859a83294d93)
![image](https://github.com/prayag17/JellyPlayer/assets/63129604/47ca9c5c-300e-42d0-9685-c5dffad0c359)
![image](https://github.com/prayag17/JellyPlayer/assets/63129604/988844c6-8d3b-4bc9-8e48-f24fcbcb7356)

**Desktop (please complete the following information):**
 - Windows 11

**Comment by prayag17** [comment]
Already know issue #266

**Comment by BNX070** [comment]
> Already know issue #301
> 
> Also you should use the latest dev build. You should also verify if you have all Media Foundation codecs installed for best playback support 

The issue stated above is with music, mine is with video. 

I have all codes installed and the video does play fine on Jellyfin windows app.

**Comment by prayag17** [comment]
Jellyfin Media Player uses MPV and has nothing to do with Media Foundation Codecs
