### ISSUE TITLE
x265/HEVC not playing

### ISSUE THREAD

**Issue by SauceageTF** [prayag17/JellyPlayer#335]
All HEVC and x265 encoded video fails to play.
There is no log in the Jellyfin dashboard being made

**Comment by prayag17** [comment]
What OS are you using?

**Comment by MulverineX** [comment]
@prayag17 I can reproduce, I'm on Windows 11 using the latest release.
![image](https://github.com/user-attachments/assets/8c31ebb5-e401-45f2-bf9c-d2e1f50b0ace)
