### ISSUE TITLE
Support trickplay in jellyfin 10.9.0

### ISSUE THREAD

**Issue by realSZ27** [prayag17/JellyPlayer#336]
**Is your feature request related to a problem? Please describe.**
I don't think so. I've only used trickplay (and jellyscrub before it) for scrub previews, so I don't really know if it works with normal chapter images.

**Describe the solution you'd like**
When scrubbing the bar, the preview will show up like on jellyfin-web.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by prayag17** [comment]
This is planned

**Comment by prayag17** [comment]
closing in favor of #337
