### ISSUE TITLE
movies not playing on linux

### ISSUE THREAD

**Issue by jjgalvez** [prayag17/JellyPlayer#4]
First really cool project, at the moment I'm watching and occasionally building /testing it, so this is just a bug report, do what you want with it, and happy to test on linux if its helpful.
1) when I try to watch a movie, it loads the background images and does nothing. when I kill the movie I get an error that says the browser does not support playing this movie. If I load the server in a browser the movies plays as expected. 
2) when you kill the server.py process with os.kill you are passing "0" which does not kill the process, I would suggest importing signal and either passing signal.SIGTERM, rather than 0. 

Also you are using the default 5000 port for flask, I would suggest picking a random open port although honestly I have no idea how you would pass that to your webengineview url dynamically, so this may not be a helpful suggestion.

Either way cool project keep up the great work

**Comment by prayag17** [comment]
1. The player can't yet play movies but I am working in it
2. singnal.SIGTERM for some reason didn't kill the process on windows that is why for now I am using 0 but that also going to be fixed

**Comment by jjgalvez** [comment]
> 1. The player can't yet play movies but I am working in it
> 2. singnal.SIGTERM for some reason didn't kill the process on windows that is why for now I am using 0 but that also going to be fixed

makes sense, I don't think SIGTERM is a thing on windows, you might have to check the os first and then use either 0 or SIGTERM
