### ISSUE TITLE
Hamburger menu doesn't do anything

### ISSUE THREAD

**Issue by Maltavius** [prayag17/JellyPlayer#73]
**Describe the bug**
Pressing the Hamburger menu at the top left doesn't do anything

**To Reproduce**
Pressing the Hamburger menu at the top left doesn't do anything
**Expected behavior**
A menu should pop out, or the left sidebar should grow.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro

**Additional context**

**Comment by prayag17** [comment]
Checkout https://github.com/prayag17/JellyPlayer/issues/11
