### ISSUE TITLE
Add Server menu does not recognize servers not using HTTPS or using the :8096 port.

### ISSUE THREAD

**Issue by Enstrayed** [prayag17/JellyPlayer#74]
**Describe the bug**
The Add Server menu upon first launching the app does not recognize any servers using http://, not using a FQDN [citation needed] or using the :8096 port [citation needed]. The only way I found to connect to my server is to use Tailscale MagicDNS and Caddy to handle HTTPS and get a FQDN. 

JellyPlayer needs to
- be able to connect to servers not using HTTPS
- be able to connect to servers not using port 80/443 (maybe)
- be able to connect to servers using a flat hostname in DNS (eg. rosebud instead of rosebud.local, rosebud.lan, rosebud.tswhatever.net)

This seems like just an input validation bug. JMP does not experience this issue.

**To Reproduce**
1. Go to Add Server menu
2. Enter any address as described above
3. Observe the failure

**Expected behavior**
As with JMP, any inputted address should be checked to see if its valid, instead of relying on input validation. 

**Screenshots**
![Error 1](https://i.enstrayed.com/20230510-CESIUM-9fef.png)
![Error 2](https://i.enstrayed.com/20230510-CESIUM-6b1c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Version 22H2 OS Build 22624.1755
 - Browser: Not Applicable (Standalone Application)
 - Version: Not Applicable (Standalone Application)

**Smartphone (please complete the following information):**
Section removed; not applicable.

**Additional context**

**Comment by prayag17** [comment]
I am not able to reproduce this error with my server. 
> be able to connect to servers using a flat hostname in DNS (eg. rosebud instead of rosebud.local, rosebud.lan, rosebud.tswhatever.net)

I will look into it

**Comment by Enstrayed** [comment]
It doesn't. JMP just takes whatever it's given and tries to contact that address. However, I was only able to get JellyPlayer to contact my server if it was over https and used a fqdn.

**Comment by prayag17** [comment]
Weird, I am able to use localhost as well as ip without http

**Comment by prayag17** [comment]
I am now using the server validation code from jf-vue so it should work as expected

**Comment by MaitrePacha** [comment]
![Capture d'écran 2023-05-11 132003](https://github.com/prayag17/JellyPlayer/assets/65720309/a0622e71-94ae-4f29-ba69-2709ca76adbc)
same issue here

**Comment by prayag17** [comment]
Try with the latest commit,  don't use the build files

**Comment by prayag17** [comment]
Does your address work with jf vue? Cause I got the code from there

**Comment by MaitrePacha** [comment]
What do you mean by jf vue ? The web interface ?

**Comment by prayag17** [comment]
Jellyfin vue

**Comment by MaitrePacha** [comment]
well i don't know jellyfin vue so i don't know

**Comment by stanol** [comment]
I have same error as @MaitrePacha and yes my address works with js-vue.

**Comment by prayag17** [comment]
Can you run the app with npm run tauri dev and try again?

**Comment by Enstrayed** [comment]
Using the Public Test Build 2 on the releases page, there has been no changes to the problem I reported. This issue should be reopened until everyone can confirm it's working. 
I'm going to try setting up some monitoring tools to see if I can deduce where the problem is then report back. I have a sneaking suspicion that there is a problem with the input validation and that it's not actually sending any requests to the inputted address.

**Comment by Enstrayed** [comment]
Yeah I'm leaning pretty hard on there still being an issue with input validation. I got TCPView setup and was only able to get a connection when I used https:// with a FQDN:
![](https://i.enstrayed.com/20230511-CESIUM-652a.png)
All other addresses/dns names/using a port/using http didn't work, as is with the original report.

I'm gonna try setting up Jellyfin Vue to test it's input validation with my setup.

**Comment by MaitrePacha** [comment]
I leave the page open to see all the news concerning the issue, here it goes a little beyond my skills but do not hesitate to identify me if you want me to test my side. Thank you for your work prayag

**Comment by prayag17** [comment]
The issue is not with the validation, something gets broken when app is built

**Comment by Enstrayed** [comment]
Spun up the latest Jellyfin-vue [Docker container ](https://github.com/jellyfin/jellyfin-vue/pkgs/container/jellyfin-vue/92107916?tag=unstable.2023-05-10.ea3e022) and was able to verify it works with any address passed to it.

**Comment by prayag17** [comment]
Found the bug, fixing it

**Comment by prayag17** [comment]
Unfortunately, this seems to be an issue with Tauri :( I am working to fix it but it will take sometime

**Comment by prayag17** [comment]
unfortunately, it turns out Tauri blocks XHR requests in production mode :( and the same thing happens with Jellyfin-Vue, i am trying to find a way around it

**Comment by prayag17** [comment]
FINALLY!!!! Finally found a fix. 
@Enstrayed Can you confirm that the issue is fixed? use https://github.com/prayag17/JellyPlayer/releases/tag/v0.0.1-publictest03 

It might take sometime for the build exe to appear since they are currently being built

**Comment by Enstrayed** [comment]
Latest build works

**Comment by prayag17** [comment]
Finally. Weird that I never encountered that issue in older builds

**Comment by MaitrePacha** [comment]
I'm going to try this right away thanks!

**Comment by MaitrePacha** [comment]
It worked for me during 15 min but now I have this error message. The work is really amazing, I can't wait to see the continuation.
![image](https://github.com/prayag17/JellyPlayer/assets/65720309/49171a90-ac59-45ba-bd58-0bc95523e2b7)

**Comment by stanol** [comment]
Same. After a successful login I see my movies but "Play" button is inactive and I can't open movie page (More info). After restarting I get error like above.

**Comment by prayag17** [comment]
The play button is inactive since playback is wip. I am working on the above issue
